FROM python:3.12-slim

LABEL maintainer="Supphachoke Suntiwichaya <mrchoke@gmail.com>"

COPY requirements.txt /requirements.txt
RUN pip install uv \
  && uv pip install --system -r /requirements.txt

CMD ["uv", "pip", "list", "--format" ,"freeze"]