FROM python:3.12-slim

LABEL maintainer="Supphachoke Suntiwichaya <mrchoke@gmail.com>"

ENV VIRTUAL_ENV /usr/local

COPY requirements.txt /requirements.txt
RUN pip install uv \
  && uv pip install -r /requirements.txt

CMD ["uv", "pip", "freeze"]